### ISSUE TITLE
只输入命令 ts 时，会报错

### ISSUE THREAD

**Issue by whoma** [hewentaowx/yd_translate#1]
https://github.com/hewentaowx/yd_translate/blob/8c93f43a976a617fcf1b3b3b866fcdc5b3017c04/src/index.js#L18

如未输入查询词时，建议来个非空判断，若为空则输出与输入 ts -h 一样的显示。

**Comment by hewentaowx** [comment]
@whoma 你好！谢谢提醒，已修正，最近比较忙就没注意这个issue，再次感谢！
